### ISSUE TITLE
Add briggs weighting options to control beamshape for mk data

### ISSUE THREAD

**Issue by bennahugo** [ratt-ru/pfb-clean#30]
Think this is the most essential option that is currently missing. There is no way to currently force the beam to a more Gaussian form so that flank contamination can be eliminated. This is a bit of a problem working in the plane where there is a ton of background diffuse emission that can be hidden by foreground HII, etc.

As discussed at the end here: https://skaafrica.atlassian.net/wiki/spaces/ESDKB/pages/41091107/Sensitivity+calculators

**Comment by landmanbester** [comment]
Should be working now, will appreciate if someone can give it a test drive

**Comment by landmanbester** [comment]
This went in a while ago. Please reopen as/if you encounter issues @bennahugo
