### ISSUE TITLE
Typical MeerKAT image size hits the zarr 2 GB chunk limit

### ISSUE THREAD

**Issue by IanHeywood** [ratt-ru/pfb-clean#69]
When trying to grid some visibilities using my standard image (10240 x 10240) and cell (1.1 arcsec) sizes I run into the following because of the double-sized PSF image:

```
ValueError: Column PSF has a chunk of dimension (16384, 16384) that will exceed zarr's 2GiB chunk limit
```

8192 x 8192 images also triggers this. 4096 x 4096 is working but I think support for larger images is essential. Is the chunk size tunable?

Thanks.

**Comment by landmanbester** [comment]
Ah must have broken that recently, should rechunk before writing. Will add a fix for that. The PSF size relative to the image size can be set with --psf-oversize
