### ISSUE TITLE
Generate primary beams

### ISSUE THREAD

**Issue by KshitijT** [ratt-ru/pfb-clean#8]
From what I understand, I need preexisting primary beams to make use of power_beam_maker.py (which interpolates)? Can we not make those directly from Eidos or something?

**Comment by landmanbester** [comment]
Indeed we could. I'll look into it when I get back from holiday next week

**Comment by landmanbester** [comment]
Tracking this here https://github.com/ratt-ru/pfb-clean/issues/1
