### ISSUE TITLE
There is a problem with conversion between hyphen and underscore in the opts dict

### ISSUE THREAD

**Issue by y-mhiri** [ratt-ru/pfb-clean#92]
When the stimela options that contains hyphens are changed to underscore all the variables are not modified.

In workers/grid.py : 

              defaults = {}
              for key in schema.grid["inputs"].keys():
                  defaults[key.replace("-", "_")] = schema.grid["inputs"][key]["default"]

The schema.grid["inputs"] doesn't have 'log-directory', 'output-filename' and all options stored in a .yml.
They are not converted to underscore and their opts value is NoneType, leading to a ValueError.

**Comment by landmanbester** [comment]
Fixed in https://github.com/ratt-ru/pfb-clean/pull/91
