### ISSUE TITLE
Pip install looking for a quartical version which doesn't seem to exist

### ISSUE THREAD

**Issue by TariqBlecher** [ratt-ru/pfb-clean#98]
@JSKenyon 
Running Python 3.10.13
On PFB-Clean main branch
Even though I have installed QuartiCal independently in the venv (via pip3 install quartical), I still get this resolution error:

(pfb_env) blecher@tina:~$ pip3 install -e pfb-clean/
Obtaining file:///home/blecher/pfb-clean
  Preparing metadata (setup.py) ... done
Collecting QuartiCal@ git+https://github.com/ratt-ru/QuartiCal.git@v0.2.0-dev (from pfb-clean==0.0.1)
  Cloning https://github.com/ratt-ru/QuartiCal.git (to revision v0.2.0-dev) to /tmp/pip-install-n6a5tyie/quartical_834f785db8ac443ab89aef0a591d2d7e
  Running command git clone --filter=blob:none --quiet https://github.com/ratt-ru/QuartiCal.git /tmp/pip-install-n6a5tyie/quartical_834f785db8ac443ab89aef0a591d2d7e
  WARNING: Did not find branch or tag 'v0.2.0-dev', assuming revision or ref.
  Running command git checkout -q v0.2.0-dev
  error: pathspec 'v0.2.0-dev' did not match any file(s) known to git
  error: subprocess-exited-with-error
  
  × git checkout -q v0.2.0-dev did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× git checkout -q v0.2.0-dev did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

**Comment by JSKenyon** [comment]
Are you on `master` or `main`? I am guessing you may be on `master` as it still has a pinned QC dependency.

**Comment by TariqBlecher** [comment]
Thanks John, yeah that was the issue.

**Comment by landmanbester** [comment]
Use the fastim branch, I've added a few improvements. Also QuartiCal main still has the stimela version pinned too low for what I need in pfb
